### ISSUE TITLE
Documentation: how to specify source dataset

### ISSUE THREAD

**Issue by Pakillo** [dgrechka/Rfc#1]
Hello,

Thanks for the package! Very useful. I ran [some quick examples](https://gist.github.com/Pakillo/df07cd13a577f2a7d03657eaaf81512f#file-rfetchclimate-md) and it worked perfectly.

But I cannot find out how to specify a given source dataset. The default (dataSets = "ANY") seems to download data from just one (NCEP/NCAR in my examples). I can't find (either in the function documentation or FetchClimate website) how to name each dataset. 

It would be nice if these dataset names were given in the documentation (and perhaps those for the different climatic variables too - although these can indeed be obtained from the website).

Again, thanks a lot

Paco

**Comment by dgrechka** [comment]
Hi,

Thank you for the feedback.

Another option can be adding another function FcGetDataCatalog to the package. This function can return object containing available climatic variables and available data sets.

Can it be helpful?

The reason I  am proposing this is that there can be different instances of FetchClimate deployed at different URLs, they can have different sets of variables and datasets available.
The FcGetDataCatalog function could be useful for getting information about variables and data sets from any of the FetchClimate instances, not only from the default one.

Regards,
Dmitry.

**Comment by Pakillo** [comment]
Hi,
Sorry for the delay. Yes, including a new FcGetDataCatalog function would be very helpful. Plus, I would include in the documentation the names of all the datasets and variables potentially available, so that one does not have to peruse the website to find them.
Thanks a lot!

**Comment by dgrechka** [comment]
fixed in 86e5688c16a0698c92007df13e8a81beb148c8ea

Now there is "Available data" section in documentation

There are also fcDataSets() and fcVariables() function available
